general.import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
#decorations = "buttonless"
dynamic_padding = false
opacity = 0.95

[window.padding]
x = 25
y = 20

[font]
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

# Keyboard bindings for better history navigation
[[keyboard.bindings]]
key = "Up"
mods = "Alt"
chars = "\u001b[1;3A"

[[keyboard.bindings]]
key = "Down"
mods = "Alt"
chars = "\u001b[1;3B"

[[keyboard.bindings]]
key = "Up"
mods = "Command"
chars = "\u001b[1;9A"

[[keyboard.bindings]]
key = "Down"
mods = "Command"
chars = "\u001b[1;9B"
