repos:
  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--allow-multiple-documents']
      - id: check-json
        exclude: ^zed/settings\.json$
      - id: check-toml
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: detect-private-key

  # Nix formatting with Alejandra (using system binary)
  - repo: local
    hooks:
      - id: alejandra
        name: alejandra
        description: Format Nix files with Alejandra
        entry: alejandra
        language: system
        files: ^nix-darwin/.*\.nix$
        pass_filenames: true

  # Nix flake checker
  - repo: local
    hooks:
      - id: nix-flake-check
        name: nix flake check
        entry: bash -c 'cd nix-darwin && nix flake check --no-build'
        language: system
        files: ^nix-darwin/.*\.nix$
        pass_filenames: false

  # Security scanning with checkov
  # Note: Currently throws too many warnings; deal with that in the future...
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 3.2.435
    hooks:
      - id: checkov
        args: [-d ., --quiet, --compact]
        # Optional: Skip specific checks that are too noisy
        # args: [-d ., --quiet, --compact, --skip-check CKV_*]
